spring:
  application:
    name: credit-application-system
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: agnaldo
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8081